"""
services/reporting_service.py — Service for session logging and findings.
"""
from __future__ import annotations
import datetime
import os
from utils.logging import get_logger

log = get_logger("services.reporting")

class ReportingService:
    """Service to maintain a local markdown file with findings and writeups."""

    def __init__(self, filepath: str = "mcp_session_notes.md"):
        self.filepath = filepath
        self._ensure_file()

    def _ensure_file(self):
        if not os.path.exists(self.filepath):
            with open(self.filepath, "w", encoding="utf-8") as f:
                f.write("#Session Notes & Findings\n\n")
                f.write("Generated by AdaptixC2 MCP Agent.\n\n---\n")

    def add_finding(self, agent_id: str, category: str, content: str, context: str = ""):
        """Add a structured finding to the log."""
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        entry = (
            f"## [{timestamp}] {category} (Agent: {agent_id})\n"
            f"**Context:** {context}\n\n"
            f"```\n{content}\n```\n\n"
            "---\n"
        )
        with open(self.filepath, "a", encoding="utf-8") as f:
            f.write(entry)
        log.info("reporting.add_finding", agent_id=agent_id, category=category)

    def add_writeup(self, agent_id: str, title: str, content: str):
        """Add a short writeup (e.g., elevation steps)."""
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        entry = (
            f"### WRITEUP: {title} ({timestamp})\n"
            f"**Agent:** {agent_id}\n\n"
            f"{content}\n\n"
            "---\n"
        )
        with open(self.filepath, "a", encoding="utf-8") as f:
            f.write(entry)
        log.info("reporting.add_writeup", agent_id=agent_id, title=title)

    def read_notes(self) -> str:
        """Read the entire notes file."""
        if not os.path.exists(self.filepath):
            return "No notes found."
        with open(self.filepath, "r", encoding="utf-8") as f:
            return f.read()
